### ISSUE TITLE
找不到code-box-shape样式

### ISSUE THREAD

**Issue by zhuchuanwu** [ant-design/ant-motion#119]
我复制官网写好的demo，但是什么也不显示，我分析是没有引用到code-box-shape这个样式

**Comment by jljsj33** [comment]
这个我要怎么回答你？
```css
.code-box-shape {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    margin: auto;
    width: 50px;
    height: 50px;
    border-radius: 4px;
    background: #019bf0;
}
```
