### ISSUE TITLE
banner动画切屏会影响覆盖层

### ISSUE THREAD

**Issue by Manning0523** [ant-design/ant-motion#235]
比如首页banner上覆盖有绝对定位的导航栏浮于上方，每次切换banner图片时导航也消失造成切屏白屏，请问有解决办法吗？

**Comment by jljsj33** [comment]
能提供重现 demo 吗？？

**Comment by Manning0523** [comment]
[http://page-daily.cainiao-inc.com/lemo/iot-data-center/index.html#/](url)
这个demo页面，导航栏和浮动的覆盖层都会随banner图片切换而消失，可以通过配置解决吗？ @jljsj33

**Comment by jljsj33** [comment]
```css
.content0-wrapper,
.header0 {
  z-index: 2
}
```
