### ISSUE TITLE
使用rc-scroll-anim 组件在页面内部内容区域超出内容无法滚动

### ISSUE THREAD

**Issue by hqwlkj** [ant-design/ant-motion#404]
css 

``` css
 .time-warp {
        position: relative;
        border: 1px solid #e2e2e2;
        padding: 20px;
        height: 520px;
        overflow-y: auto; //  这里设置了超出部分 Y轴滚动。
}
```

图片中的两个区域都不能用鼠标来控制进行滚动

![image](https://user-images.githubusercontent.com/12181423/94360078-7673b900-00dd-11eb-8601-6820c8bea222.png)

只有通过用鼠标选择内容后进行拖拽功能 
![image](https://user-images.githubusercontent.com/12181423/94360090-a15e0d00-00dd-11eb-840f-15fee02c5e14.png)
