### ISSUE TITLE
Ant Motion opening animation

### ISSUE THREAD

**Issue by partitect** [ant-design/ant-motion#62]
How to edit opening animation 
http://codepen.io/telatkaya/pen/zNMXjX

**Comment by jljsj33** [comment]
http://codepen.io/jljsj33/pen/RpjQvw


load animate add:

```css
#ant-motion-load ul li {
   list-style-type: none;
} 
```
